import './components/_header';
import './components/_nav-menu';
import './components/_animations';
import './components/_dynamic-vh'
import './components/_parallax';
import './components/_gallery';
import './components/_counters';
import './components/_slider';
import './components/_contacts-map';
